### ISSUE TITLE
Incompatible with laravel/framework v7.*

### ISSUE THREAD

**Issue by abejenaru** [TishoTM/eloquent-ci-relations#2]
Hi and thanks so much for your work!
Do you think you can extend the compatibility to all minor v7.* versions ?
Cheers!

**Comment by TishoTM** [comment]
@abejenaru, I will take a look during the upcoming days. Can you share in the meantime what you are experiencing and having trouble with?
Cheers!

**Comment by abejenaru** [comment]
Hi, thanks for looking into this!
I think it's a dependency definition problem within the composer file:

Using the latest Laravel version:

`laravel new test1`
`composer require tishotm/eloquent-ci-relations`

the output is:

  Problem 1
    - Installation request for tishotm/eloquent-ci-relations dev-master -> satisfiable by tishotm/eloquent-ci-relations[dev-master].
    - Conclusion: remove laravel/framework v7.25.0
    - Conclusion: don't install laravel/framework v7.25.0
    - tishotm/eloquent-ci-relations dev-master requires illuminate/database >=5.5 <=7

Cheers!

**Comment by TishoTM** [comment]
Try putting `"minimum-stability": "dev"` in the composer.json file.

**Comment by TishoTM** [comment]
@abejenaru, just pushed a big update including the support of Eloquent 7 and HasOneThrough relation.
Closing the issue for now but feel free to re-open it if you need more help.
Cheers!
