### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by fruzin** [TishoTM/eloquent-ci-relations#9]
PS C:\xampp\htdocs\laravel10> composer require tishotm/eloquent-ci-relations
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update tishotm/eloquent-ci-relations
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tishotm/eloquent-ci-relations v1.0.0 requires illuminate/database ^5.5.33 || ~6.0 || ~7.0 || ~8.0 -> found illuminate/database[v5.5.33, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - tishotm/eloquent-ci-relations v1.0.1 requires illuminate/database ^5.5.33 || ^6.20.26 || ~7.0 || ~8.0 -> found illuminate/database[v5.5.33, ..., v5.8.36, v6.20.26, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - tishotm/eloquent-ci-relations[v1.0.2, ..., v1.1.0] require illuminate/database ^5.5.33 || ^6.20.26 || ^7.30.4 || ^8.40.0 -> found illuminate/database[v5.5.33, ..., v5.8.36, v6.20.26, ..., v6.20.44, v7.30.4, v7.30.5, v7.30.6, v8.40.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - tishotm/eloquent-ci-relations v1.2.0 requires illuminate/database ^5.5.33 || ^6.20.26 || ^7.30.4 || ^8.40.0 || ^9.0 -> found illuminate/database[v5.5.33, ..., v5.8.36, v6.20.26, ..., v6.20.44, v7.30.4, v7.30.5, v7.30.6, v8.40.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires tishotm/eloquent-ci-relations * -> satisfiable by tishotm/eloquent-ci-relations[v1.0.0, ..., v1.2.0].    

You can also try re-running composer require with an explicit version constraint, e.g. "composer require tishotm/eloquent-ci-relations:*" to figure out if any version is installable, or "composer require tishotm/eloquent-ci-relations:^2.1" if you know which you need.

**Comment by TishoTM** [comment]
The PR for the support of Laravel 10 has been merged. The new release tag is v1.3.0
